### ISSUE TITLE
Generate gold standard entity detection dataset

### ISSUE THREAD

**Issue by lintool** [salman1993/simple-qa-on-kb#1]
Since we've identified entity linking as a problem we need to examine in isolation, we should generate a specific dataset for it. Using this thread as a discussion of how to best do it.

My suggestion is to just augment the original fb dataset with new fields. So, `annotated_fb_data_train.txt`:

```
www.freebase.com/m/04whkz5	www.freebase.com/book/written_work/subjects	www.freebase.com/m/01cj3p	what is the book e about
www.freebase.com/m/0tp2p24	www.freebase.com/music/release_track/release	www.freebase.com/m/0sjc7c1	to what release does the release track cardiac arrest come from
...
```

Tack on the following column, from the official alias:

```
e
cardiac arrest
```

In most cases, the alias should be a proper substring of the question, but there might be cases in which it doesn't match exactly.

My suggestion is to write a script that generates this file and include the Python script in the repo.

Thoughts @salman1993 and @Impavidity ?

**Comment by lintool** [comment]
Additional comment - we should prep data to isolate the entity detection problem also. If the question is "to what release does the release track cardiac arrest come from" and the entity is "cardiac arrest", the simplest would be to represent a bit vector: `00000001100` (space tokenized, 1 for "entity", 0 for "not entity").

**Comment by salman1993** [comment]
1) I can add onto the dataset with the entity name fields. 

2) The entity detection dataset is already there if you look in entity_detection/data/...  (you have to run entity_detection/get_data.sh)

**Comment by salman1993** [comment]
I added a script "augment_dataset.py" and also edited the "fetch_dataset.sh" script to add a new augmented dataset in 'data/SimpleQuestions_v2_augmented' 

- This dataset contains a column with the entity names. These names were picked according to lowest edit-distance with the question among the possible names/alias of that entity MID from Freebase.
