### ISSUE TITLE
Loading in the FB knowledge graph as a DataFrame

### ISSUE THREAD

**Issue by lintool** [salman1993/simple-qa-on-kb#19]
If we load in the FB knowledge graph as a DataFrame, we can interactively explore it and play around.

@salman1993 please set up a "stub" iPython notebook that contains the boilerplate of loading everything?

**Comment by salman1993** [comment]
https://github.com/salman1993/BuboQA/blob/master/ferhan_simple_qa_rnn/exploration/explore-fb-subset.ipynb

**Comment by lintool** [comment]
I've done this, with Python notebooks for exploration, stored at: https://github.com/castorini/BuboQA/tree/master/exploration
