### ISSUE TITLE
iPython notebook for e2e system

### ISSUE THREAD

**Issue by lintool** [salman1993/simple-qa-on-kb#2]
Hi @salman1993 can you build an iPython notebook for the e2e system? I want to put in "when was albert einstein born" and get back something like [mid, 'albert einstein', rel].

**Comment by salman1993** [comment]
Let's break this story up:
- In entity detection text preprocessing, give me a function called get_query_text(question) that takes in text of one question and returns the query text, i.e "where was sasha vujacic born?"  => "sasha vujacic"   ---> assigning this to @Impavidity 
- then there is relation prediction and entity linking . ----> assigning the rest to me
