### ISSUE TITLE
Storage solution for the knowledge graph

### ISSUE THREAD

**Issue by lintool** [salman1993/simple-qa-on-kb#3]
@salman1993 IIRC, your code builds various indexes on the kg, but you don't actually index the graph itself. So if the question were "when was albert einstein born" and we get back something like [mid, 'albert einstein', rel], we still need some functionality to actually _look up_ the triple from the kg, right?

We should probably use some sort of DB? Poking around, there are some options:
+ [CodernityDB](http://labs.codernity.com/codernitydb/)
+ [ZODB](http://www.zodb.org/)
+ [PyDbLite](https://pydblite.readthedocs.io/en/latest/)
+ [tinydb](https://pypi.python.org/pypi/tinydb)

Perhaps think about storing the index structures in the same db?

**Comment by salman1993** [comment]
The 2M subset of Freebase augmented with names is around 800 MB. I think we can just dump it as a pickle and load it up pretty quickly. Ideas?
