### ISSUE TITLE
FB5M.name.txt can not be downloaded

### ISSUE THREAD

**Issue by zjjj** [salman1993/simple-qa-on-kb#47]
Hi,
Just want to let you know that the link to file "FB5M.name.txt" is broken. What the following line in `scripts/fetch_dataset.sh` is saving a 404 webpage to the txt file.
```
wget https://www.dropbox.com/s/yqbesl07hsw297w/FB5M.name.txt
```

**Comment by salman1993** [comment]
Thanks for filing the issue. I deleted the file by mistake - we'll fix this soon.

**Comment by Impavidity** [comment]
@zjjj I fix the link problem and you can update the script. 
Thanks for letting us know this issue.
If you have any further problem, please let me know.

**Comment by zjjj** [comment]
The new link is good. Thanks much for your quick responses.
