### ISSUE TITLE
UnicodeDecodeError for entity_detection

### ISSUE THREAD

**Issue by zjjj** [salman1993/simple-qa-on-kb#48]
I met the following error for entity_detection:
```
$ python train.py --entity_detection_mode LSTM --fix_embed
Note: You are using GPU for training
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    train, dev, test = SQdataset.splits(TEXT, ED, args.data_dir)
  File "BuboQA-master/entity_detection/nn/sq_entity_dataset.py", line 10, in splits
    ('obj', None), ('text', text_field), ('ed', label_field)]
  File "anaconda2/envs/pytorch/lib/python3.6/site-packages/torchtext/data/dataset.py", line 76, in splits
    os.path.join(path, train), **kwargs)
  File "anaconda2/envs/pytorch/lib/python3.6/site-packages/torchtext/data/dataset.py", line 235, in __init__
    examples = [make_example(line, fields) for line in reader]
  File "anaconda2/envs/pytorch/lib/python3.6/site-packages/torchtext/data/dataset.py", line 235, in <listcomp>
    examples = [make_example(line, fields) for line in reader]
  File "anaconda2/envs/pytorch/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 4585: invalid continuation byte
```
My torchtext version is 0.2.3, not sure if that's why I met the problem.
Thanks!

**Comment by zjjj** [comment]
I downgraded to torchtext 0.2.0 but still got the same problem...
```
$ pip list
certifi (2018.1.18)
chardet (3.0.4)
idna (2.6)
numpy (1.14.2)
Pillow (5.0.0)
pip (9.0.3)
PyYAML (3.12)
requests (2.18.4)
setuptools (36.4.0)
six (1.11.0)
torch (0.3.1)
torchtext (0.2.0)
torchvision (0.2.0)
tqdm (4.22.0)
urllib3 (1.22)
wheel (0.29.0)
```

**Comment by Impavidity** [comment]
could you try to clone torchtext from source to checkout to commit id 26bd6fde43a9a07bf5982390ce7580c1aa2f13f0 to see if this problem still happens ?

**Comment by Impavidity** [comment]
@zjjj  I check the version with 0.2.0 and 0.2.3, and I did not replicate the issue you have.
I will check if there is any other possible reason causing this.

Thank you for letting us know these existing issues !

**Comment by zjjj** [comment]
I think the problem is with the preprocessed data. I end up running the whole `setup.sh` pipeline again and now the problem is solved. Thanks again for your quick response.

**Comment by Impavidity** [comment]
@zjjj Thanks for letting us know.

**Comment by rashad101** [comment]
Inside the scripts/ folder in all the python files wherever I found any file read or file write operation on *.txt files, I've added encoding="utf-8"
 that solves the UnicodeDecodeError for me.  So this way when you run the setup.sh file the preprocessing will be done with correct encoding of text.
