### ISSUE TITLE
Stanford NER baseline for entity detection

### ISSUE THREAD

**Issue by lintool** [salman1993/simple-qa-on-kb#5]
Let's run an entity detection baseline using Stanford NER straight out of the box.

**Comment by lintool** [comment]
@Impavidity As discussed this afternoon, please check in the code that does this - send PR.

**Comment by salman1993** [comment]
Test set results:
NER stands for Stanford NER 
LR trained on (train+valid) set with averaged word2vec embeddings + top 300 relation words
RNNs trained on only train set, tuned on valid set

- crossing (<=) 20 entities X 5 relations
```
Entity      Relation    Retrieval   Ret@1   Ret@2   Ret@3
------------------------------------------------------------
NER         LR          74.5        62.2    68.8    70.7
NER         RNN         79.0        67.7    73.9    75.7
RNN         LR          75.5        62.7    69.6    71.6
RNN         RNN         80.1        68.4    74.8    76.7
```
For reference: memory networks get 62.7% accuracy and our (NER, LR) combination is getting 62.2% currently without any NNs.

Comments:
- NER seems to be good enough replacement for RNN
- LR is doing really bad compared to RNN

**Comment by Impavidity** [comment]
A minor correction here, the word embedding I used for  Average Embedding + top 300 relation in LR is word2vec.

**Comment by salman1993** [comment]
RNN + RNN (with indegree 2nd sorting) 

on test set:
retrieved at top 1: 69.8947173136682
retrieved at top 2: 76.15602244793841
retrieved at top 3: 77.92773990074672
retrieved at inf:   81.57321089003293

on dev set:
retrieved at top 1: 70.76566125290023
retrieved at top 2: 76.69605568445476
retrieved at top 3: 78.67285382830627
retrieved at inf:   82.19025522041763
