### ISSUE TITLE
load data issue

### ISSUE THREAD

**Issue by coldplaying42** [salman1993/simple-qa-on-kb#54]
I am using torch0.4 and torchtext0.2.3.  When I load the train, dev and test data. I find that TEXT.vocab.num is 12. How to fix the issue?

**Comment by coldplaying42** [comment]
Could the current code run on torch0.4 and torchtext0.2.3?

**Comment by lintool** [comment]
Hi @coldplaying42 - this is already in our plans, as part of #53

**Comment by coldplaying42** [comment]
Hi @lintool , I am very glad for receiving your response. I have solved the problem. I want to run an end-to-end system, does codes in the folder alice-api-code support the end-to-end function (e.g., input a question and return an answer)?

**Comment by Impavidity** [comment]
Hi @coldplaying42 Thanks for your interest on the demo. Currently Alice-api-code is not properly maintained.  #10 Will revisit this at some point.
