### ISSUE TITLE
model.eval() , error: AttributeError 'tuple' object has no attribute 'eval'

### ISSUE THREAD

**Issue by simba0626** [salman1993/simple-qa-on-kb#58]
When running top_retrieval.py in 'nn' folder, I meet one question:
model is' tuple' object, and it has no attribut 'eval'

![default](https://user-images.githubusercontent.com/8748445/44185099-ecf30e00-a144-11e8-87d4-66144bac20a5.PNG)

Do you help me?

**Comment by simba0626** [comment]
In addition, I edit one line (Because I do not have GPU), as follows:
#model = torch.load(args.trained_model, map_location= lambda storage,location: storage.cuda(args.gpu))  //source
model = torch.load(args.trained_model, map_location= lambda storage, location: storage) //local place

**Comment by nlpjoe** [comment]
It seems like your model doesn't load correctly, try as below:
```
model = torch.load(args.trained_model)
```

**Comment by simba0626** [comment]
Thank you. nlpjoe.
I make a mistake: args.trained_model configuration is error. I think It leads to load() error.
Now, it seems work.

**Comment by Impavidity** [comment]
Is this issue solved @simba0626

**Comment by simba0626** [comment]
Thanks, this question is solved.

**Comment by Impavidity** [comment]
Good to know ! Thanks for your interests in this project.
