### ISSUE TITLE
Reorganize directory structure, moving common data out of ferhan_simple_qa_rnn

### ISSUE THREAD

**Issue by lintool** [salman1993/simple-qa-on-kb#7]
Currently, everything is in the `ferhan_simple_qa_rnn/` directory. It would make sense to move data-processing scripts etc. to top level - might want to reorganize directory structure while you're at it. A suggestion might be:

+ `relation_prediction/`
+ `relation_prediction/tj_rnn/` (tj for Ture and Jojic)
+ `relation_prediction/lr_baseline/`
+ etc.

**Comment by salman1993** [comment]
This is the structure we decided on:
```
- data/
- scripts/
- entity_detection/rnn
             /crf
                  /results
                  /query-text
- relation_prediction/rnn
            /cnn
            /lr
                   /results
- entity_linking/
                   /results
- evidence_integration/
- indexes/
- setup.sh
```
